### ISSUE TITLE
Frontend: submit data entry using correct polling station information

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#108]
Make sure that the data entry page uses the correct polling station information (id, number, name) from the polling station that was selected and also submit to the data entry API endpoint using the that id.

Cases to consider:
- existing polling station number
- non-existing polling station number
- not a number, e.g. "asd", to be handled the same as non-existing polling station number, see [comment](https://github.com/kiesraad/abacus/pull/146#discussion_r1682879672) in earlier PR
- no polling station number (user immediately clicks "Beginnen" without inputting a polling station number)

Submitting through the keyboard should not happen on "Enter", only on "Shift + Enter".

**Comment by cikzh** [comment]
@jorisleker As far as I can tell the design doesn't specify what happens to the "Beginnen" button when an invalid station number is entered. Should we disable the button until a valid and existing polling station is entered? Or should clicking the button just "do nothing"?

**Comment by praseodym** [comment]
> Cases to consider:
> 
> * existing polling station number
> * non-existing polling station number
> * not a number, e.g. "asd", to be handled the same as non-existing polling station number, see [comment](https://github.com/kiesraad/abacus/pull/146#discussion_r1682879672) in earlier PR
> * no polling station number (user immediately clicks "Beginnen" without inputting a polling station number)
> 
> Submitting through the keyboard should not happen on "Enter", only on "Shift + Enter".

@jschuurk-kr you added these items to the issue description but they are not about the data entry form but the polling station select page, which was done in #107. Can you confirm that these points are resolved now?

**Comment by jschuurk-kr** [comment]
>  > \<snipped\>

> @jschuurk-kr you added these items to the issue description but they are not about the data entry form which this issue is about, but the polling station select page that was done in #107. Can you confirm that these points are resolved now?

@praseodym It was not entirely clear to me if clicking "Beginnen" was part of #107 or not, hence that I added those cases here.

As to their status, the first three are ok. If you enter something in the input field, it's either a valid polling station number or not. If it's valid, clicking "Beginnen" gets you to the next page. If it's not valid, nothing happens.

The fourth one is not resolved. If you click "Beginnen" without inputting a polling station number, nothing happens. We should provide some feedback to the user.

**Comment by cikzh** [comment]
I considered the fourth case to be the same as @jorisleker's comment (https://github.com/kiesraad/abacus/issues/108#issuecomment-2247897940) on case 2. 
If it needs fixing I create a separate issue/PR from this one.

**Comment by jorisleker** [comment]
Yes, we can handle case 2 and 4 the same way. That is: no action needed now, but will consider adding specific feedback for those cases

**Comment by jorisleker** [comment]
Yes, agreed. We need a solution, just not in this issue

**Comment by jschuurk-kr** [comment]
> Yes, agreed. We need a solution, just not in this issue

#195

**Comment by cikzh** [comment]
@praseodym Am I correct that for this issue, we don't yet know about `entryNumber`, so it will remain hard-coded to `1`?

**Comment by praseodym** [comment]
> @praseodym Am I correct that for this issue, we don't yet know about `entryNumber`, so it will remain hard-coded to `1`?

Yes, right now only `1` is valid. The `entryNumber` will be `1` or `2` for first or second data entry (eerste of tweede invoer) once we implement the second data entry in #129.

**Comment by cikzh** [comment]
@jorisleker Since we now load data from the backend, we need to show something before the polling station is loaded. Right now I've implemented a badly aligned spinner, but is there a design available for when a whole page is loading?

**Comment by jorisleker** [comment]
@cikzh Lets go for the easiest fix: no design at all. When normal webpages load, default browser behavior is to show a blank page. No spinner, no text, no nothing. Can we do that? I think most pageloads will be that fast (<1s) that we don't really need any loading indicator.

**Comment by cikzh** [comment]
That makes sense, I will do that :+1:
